# Generated by Django 6.0.6 on 2026-06-24 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("te", "Telugu"), ("hi", "Hindi")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        choices=[
                            ("print", "Print"),
                            ("digital", "Digital"),
                            ("epaper", "E-Paper"),
                        ],
                        default="digital",
                        max_length=10,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("vizag", "Vizag"),
                            ("vizag_gajuwaka", "Vizag - Gajuwaka"),
                            ("hyderabad", "Hyderabad"),
                            ("vijayawada", "Vijayawada"),
                            ("tirupati", "Tirupati"),
                        ],
                        default="vizag",
                        max_length=20,
                    ),
                ),
                (
                    "keywords",
                    models.TextField(blank=True, help_text="Comma-separated keywords"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
